/* Telecom offers use their own billing periods; no invented monthly equivalents. */
(()=>{
 const data=window.FUELWATCH_NETWORK||{rows:[],providers:[],checked_at:null};
 const nav=document.querySelector('.nav-shell'),dashboard=document.querySelector('.utility-dashboard');
 const section=document.createElement('section');section.className='network-dashboard';section.hidden=true;dashboard.after(section);
 const titles={broadband:'Broadband 宽带价格',mobile:'Telecom 电信价格'};const buttons={};let service='broadband',provider='',period='';
 const money=n=>'₱'+Number(n).toLocaleString('en-PH',{maximumFractionDigits:2});
 const periodName=p=>p==='month'?'每月':p.replace(' days','天有效期');
 const rowsFor=s=>data.rows.filter(r=>r.service===s);
 for(const kind of ['broadband','mobile']){
  const button=document.createElement('button');button.dataset.section=kind;button.textContent=titles[kind];button.setAttribute('aria-pressed','false');button.onclick=()=>open(kind);nav.append(button);buttons[kind]=button;

 }
 nav.querySelectorAll('button:not([data-section="broadband"]):not([data-section="mobile"])').forEach(button=>button.addEventListener('click',()=>{section.hidden=true;Object.values(buttons).forEach(b=>{b.classList.remove('active');b.setAttribute('aria-pressed','false');});}));
 function open(kind){service=kind;provider='';period='';window.FUELWATCH_UPGRADE.switchSection(kind);dashboard.hidden=true;section.hidden=false;nav.querySelectorAll('button').forEach(b=>{const active=b.dataset.section===kind;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});draw();}
 function draw(){
  const offers=rowsFor(service),providers=[...new Set(offers.map(r=>r.provider))].sort(),periods=[...new Set(offers.map(r=>r.billing_period))];
  section.innerHTML=`<div class="network-heading"><h2>${titles[service]}</h2><p>${service==='mobile'?'菲律宾国内通话、短信与流量参考。普通按量资费与套餐价格分开显示；权益及有效期以对应官网确认。':'菲律宾供应商官网公开宽带套餐。价格单位、网络覆盖及最高速率不同，请按需要比较。'}</p><p class="network-date">最近检查 ${esc(data.checked_at||'暂无')} · 采集日期不是调价生效日 · 自动采集与人工核验分开</p></div><div class="network-controls"><label>供应商 <select aria-label="网络供应商"><option value="">全部供应商</option>${providers.map(p=>`<option value="${esc(p)}">${esc(p)}</option>`).join('')}</select></label><label>计费周期 <select aria-label="计费周期"><option value="">全部周期（分组显示）</option>${periods.map(p=>`<option value="${esc(p)}">${esc(periodName(p))}</option>`).join('')}</select></label></div><p class="network-caution">下方套餐表标价仅为套餐费用，不包含未核实的安装费、设备费或其他附加费用；地址覆盖、SIM、合约和促销资格以官网确认结果为准。历史采集值不会冒充今日新价。</p><div class="network-regular"></div><div class="network-results" aria-live="polite"></div><details class="network-method"><summary>数据范围与采集失败说明</summary><p>收录 PLDT、Globe、Converge、Smart、DITO、SKY、TNT 的已核验套餐。前五家既有采集器每日尝试读取；SKY、TNT及Globe Go59的套餐标价为2026-10-06人工核验；通话短信另保留各自核验日期，不随每日采集刷新核验日期。不是全市场、全套餐覆盖；个性化优惠和登录后报价不猜测。抓取失败时保留原采集日期并显示失败标记。</p>${data.providers.map(p=>`<p>${esc(p.provider)}：${p.status==='manual-verified'?'人工官网核验 '+p.observed_at:p.status==='observed'?'官网采集成功':'官网采集失败；旧值或暂无数据'} · <a href="${esc(p.source_url)}" target="_blank" rel="noopener">官方套餐页 ↗</a></p>`).join('')}</details>`;
  const filters=section.querySelectorAll('select');filters[0].value=provider;filters[1].value=period;filters[0].onchange=e=>{provider=e.target.value;results();regular();};filters[1].onchange=e=>{period=e.target.value;results();};results();regular();
 }
 function results(){
  const rows=rowsFor(service).filter(r=>(!provider||r.provider===provider)&&(!period||r.billing_period===period)),target=section.querySelector('.network-results');
  section.classList.toggle('voice-visible',service==='mobile');
  const groups=[...new Set(rows.map(r=>r.billing_period))].sort((a,b)=>a==='month'?-1:b==='month'?1:parseInt(a)-parseInt(b));
  target.innerHTML=`<p class="network-count">${rows.length} 个已收录套餐</p>`+(rows.length?groups.map(p=>`<section class="network-group"><h3>${esc(periodName(p))}${p==='month'?' · 月费宽带':' · 预付套餐'}</h3><p class="network-group-note">本组仅按标价从低到高排列；速率、流量与合约不同，低标价不等于更适合。</p><div class="network-table"><div class="network-table-head"><span>供应商 / 套餐</span><span>公开标价</span><span>速率 / 流量</span>${service==='mobile'?'<span>通话与短信 / Calls & SMS</span>':''}<span>日期 / 来源</span></div>${rows.filter(r=>r.billing_period===p).sort((a,b)=>a.price-b.price||a.provider.localeCompare(b.provider)).map(r=>`<article class="network-row"><div><b>${esc(r.provider)}</b><span>${esc(r.plan)}</span><details><summary>适用条件与费用</summary><p>覆盖：${esc(r.region)}</p><p>安装/设备费用：${r.setup_fee==null?'未统一核实，另向供应商确认':esc(money(r.setup_fee))}</p><p>锁约：${r.lock_in_months==null?(r.lockup_note?'官网注明无锁约':'未核实，详见官网'):esc(r.lock_in_months)+'个月'}</p><p>${esc(r.conditions)}</p></details></div><div class="network-price"><strong>${money(r.price)}</strong><span>${esc(periodName(r.billing_period))}</span></div><div>${r.service==='broadband'?(r.speed_mbps!=null?'<b>最高 '+esc(r.speed_mbps)+' Mbps</b>':'<b>日夜分档速率 · 见条件</b>'):'<b>'+esc(r.data_gb)+' GB</b>'}<span>${esc(r.data_allowance)}</span></div>${service==='mobile'?`<div class="network-voice"><b>通话 / Calls</b><span>${esc(r.calls_text||'未核实（非免费）')}</span><b>短信 / SMS</b><span>${esc(r.sms_text||'未核实（非免费）')}</span>${r.voice_sms_source_url?`<a href="${esc(r.voice_sms_source_url)}" target="_blank" rel="noopener">通话短信权益来源 ↗</a><span>核验 ${esc(r.voice_sms_observed_at)}</span>`:''}</div>`:''}<div><span class="network-state">${r.status==='manual-verified'?'人工官网核验':r.status==='fetch-failed'?'抓取失败 · 保留原采集值':'官网采集参考'}</span><span>${r.status==='manual-verified'?'核验':'采集'} ${esc(r.observed_at)}</span><a href="${esc(r.source_url)}" target="_blank" rel="noopener">查看官方套餐 ↗</a></div></article>`).join('')}</div></section>`).join(''):'<p>此筛选没有收录的套餐。</p>');
 }
 function regular(){
  const target=section.querySelector('.network-regular');if(service!=='mobile'){target.innerHTML='';return;}
  const voice=data.voice_sms||{regular_rows:[],gaps:[]},rows=voice.regular_rows.filter(r=>!provider||r.provider===provider);
  target.innerHTML=`<section class="regular-rates"><h3>普通通话与短信 / Pay-as-you-go</h3><p>以下按分钟或按条计费，不是套餐价。套餐包含权益请看下方独立列；未知权益不代表免费。仅列菲律宾国内参考，国际、漫游、特殊号码及计费舍入未核实。此表人工官网核验，原文件日期保留。</p><div class="regular-list">${rows.map(r=>`<article><b>${esc(r.provider)} · ${r.service==='call'?'通话 / Calls':'短信 / SMS'}</b><span>${esc(r.destination)}</span><strong>${money(r.price)} <small>${r.service==='call'?'/ 分钟 · minute':'/ 条 · SMS'}</small></strong><span>${r.published_at?'历史文章 '+esc(r.published_at)+' · 现行适用未确证':'官网公开参考 · 生效日未注明'}</span><span>人工核验 ${esc(r.observed_at)}</span><a href="${esc(r.source_url)}" target="_blank" rel="noopener">官方资费来源 ↗</a><details><summary>适用条件</summary><p>${esc(r.scope)}</p></details></article>`).join('')||'<p>本供应商普通资费尚未确证，不猜填。</p>'}</div><details><summary>未核实的通话与短信（${voice.gaps.length}家）</summary>${voice.gaps.map(g=>`<p>${esc(g.provider)}：${esc(g.reason)} <a href="${esc(g.source_url)}" target="_blank" rel="noopener">官网 ↗</a></p>`).join('')}</details></section>`;
 }
 window.ENERGY_NETWORK={open,data};
})();
