/* FuelWatch October client upgrade. Plain scripts preserve file:// support. */
(()=>{
const sourceData=window.FUELWATCH_UTILITIES||{checked_at:null,categories:[]};
const descriptions={water:['Water 水价','Commercial water depends on customer class and consumption bands.'],electricity:['Electricity 电价','Published residential reference; commercial shop rate requires its contract.'],lpg:['LPG 煤气','11 kg bottled LPG · surveyed regional prices.']};
const fmt=n=>Number(n).toLocaleString('en-PH',{maximumFractionDigits:4});
const value=c=>{const o=c.observations?.[0];if(!o)return 'No verified price';return o.value!=null?'₱'+fmt(o.value):'₱'+fmt(o.min)+'–'+fmt(o.max);};
const label=c=>c.status==='reference'?'Published reference':c.status==='historical'?'Historical reference':c.status==='fetch-failed'?'Source unavailable · last record':'No data';
const nav=document.createElement('nav');nav.className='nav-shell';nav.setAttribute('aria-label','Price categories');nav.innerHTML='<button data-section="fuel" class="active" aria-pressed="true">油价地图</button><button data-section="overview" aria-pressed="false">价格总览</button>'+sourceData.categories.map(c=>`<button data-section="${esc(c.id)}" aria-pressed="false">${esc(descriptions[c.id][0])}</button>`).join('');document.querySelector('#notice').before(nav);
const dashboard=document.createElement('section');dashboard.className='utility-dashboard';dashboard.hidden=true;dashboard.innerHTML=`<div class="utility-heading"><div><h2>油、水、电、煤气与网络价格</h2><p>菲律宾能源与通信费用参考。请先确认地区、计费周期和适用条件。</p></div><p>Official sources checked ${esc(sourceData.checked_at||'not yet')}<br>Daily source monitoring · PHP</p></div><div class="utility-grid">${sourceData.categories.map(c=>`<article class="utility-card"><h3>${esc(descriptions[c.id][0])}</h3><span class="utility-state ${c.observations?.length?'':'empty'}">${esc(label(c))}</span><div class="utility-value">${esc(value(c))}</div><p>${esc(c.observations?.[0]?.unit||'Retail tariff unverified')}</p><p>${esc(c.observations?.[0]?.provider||'Official-source monitoring')} · ${esc(c.observations?.[0]?.as_of||'No dated observation')}</p><button data-detail="${esc(c.id)}">Inspect source & scope →</button></article>`).join('')}</div><article class="utility-detail" hidden tabindex="-1"></article><details class="utility-method"><summary>How these references are monitored</summary><p>Data is collected from provider and government websites. Collection date and price date are separate. Historical figures are not current quotes; residential and commercial tariffs are not interchangeable. Missing sources stay blank. Each bill depends on tariff class, usage, additions and taxes.</p><p>Daily automated checks retain the last verified observation when a source fails, with its original date. A source-page change can require parser maintenance.</p></details>`;document.querySelector('.workspace').after(dashboard);
const tabs=[...nav.querySelectorAll('[data-section]')];
function switchSection(id){tabs.forEach(b=>{const active=b.dataset.section===id;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});const fuelView=id==='fuel';document.querySelector('.workspace').hidden=!fuelView;document.querySelector('#nearResult').hidden=!fuelView;document.querySelector('#notice').hidden=!fuelView;document.querySelector('.intro').hidden=!fuelView;dashboard.hidden=fuelView;if(fuelView){requestAnimationFrame(()=>map?.resize());return;}dashboard.querySelector('.utility-grid').hidden=id!=='overview';const detail=dashboard.querySelector('.utility-detail');detail.hidden=id==='overview';if(!detail.hidden){const c=sourceData.categories.find(c=>c.id===id),o=c.observations?.[0];detail.innerHTML=`<h3>${esc(descriptions[c.id][0])}</h3><span class="utility-state ${o?'':'empty'}">${esc(label(c))}</span><div class="utility-value">${esc(value(c))}</div><p>${esc(o?.unit||'No verified shop tariff')}</p><p class="scope-note">${esc(c.message)}</p><dl><dt>Provider</dt><dd>${esc(o?.provider||'Not identified')}</dd><dt>Applicable area</dt><dd>${esc(o?.region||'Philippines · supplier not confirmed')}</dd><dt>Observation date</dt><dd>${esc(o?.as_of||'Unavailable')}${o?.period_end?' to '+esc(o.period_end):''}</dd><dt>Collection check</dt><dd>${esc(c.checked_at)}</dd><dt>Tariff class</dt><dd>${esc(o?.scope||descriptions[c.id][1])}</dd><dt>Official source</dt><dd><a href="${esc(c.source_url)}" target="_blank" rel="noopener">Open official document ↗</a></dd></dl>`;}}
tabs.forEach(b=>b.onclick=()=>switchSection(b.dataset.section));dashboard.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>switchSection(b.dataset.detail));
// Cache all feature construction per fuel. Brand changes update GPU filters instead of rebuilding/retransferring 10k points.
const oldFeatures=features,cache=new Map();let sourceFuel=null,pending=0;
const allFeatures=()=>{if(!cache.has(fuel)){const keep=selected;selected=new Set(brands);cache.set(fuel,oldFeatures());selected=keep;}return cache.get(fuel);};
features=function(){const all=allFeatures();return {type:'FeatureCollection',features:all.features.filter(f=>selected.has(f.properties.brand))};};
refresh=function(){cancelAnimationFrame(pending);pending=requestAnimationFrame(()=>{if(popup)popup.remove();const all=allFeatures(),data=features();if(ready){const source=map.getSource('stations');if(source&&sourceFuel!==fuel){source.setData(all);sourceFuel=fuel;}const include=['in',['get','brand'],['literal',[...selected]]];map.setFilter('points',['all',['!',['has','point_count']],include]);map.setFilter('price-labels',['all',['!',['has','point_count']],['>=',['get','price'],0],include]);}const vals=prices.rows.filter(r=>r.fuel===fuel&&selected.has(r.brand)).map(r=>r.price),low=Math.min(...vals),high=Math.max(...vals);document.querySelector('#low').textContent=vals.length?'₱'+low.toFixed(2):'—';document.querySelector('#high').textContent=vals.length?'₱'+high.toFixed(2):'—';if(ready)map.setPaintProperty('points','circle-color',['case',['<',['get','price'],0],'#929c98',low<high?['interpolate',['linear'],['get','price'],low,'#168461',high,'#c34343']:'#168461']);status(`<strong>${data.features.length.toLocaleString()} stations selected</strong> / ${stations.length.toLocaleString()} nationwide · ${data.features.filter(f=>f.properties.price>=0).length} with a matched current NCR reference.<br>Week of ${esc(prices.as_of)} · Grey stations have no verified price.`);});};
const search=document.createElement('div');search.className='brand-search';search.innerHTML='<input type="search" aria-label="Search brands" placeholder="Search a brand…">';document.querySelector('.brand-actions').after(search);const filterBrands=()=>{const q=search.firstChild.value.trim().toLowerCase();document.querySelectorAll('.brand').forEach(row=>row.hidden=!row.querySelector('b').textContent.toLowerCase().includes(q));};search.firstChild.oninput=filterBrands;
const oldRender=renderBrands;renderBrands=function(){oldRender();filterBrands();};
const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduce&&map){const oldFly=map.flyTo.bind(map);map.flyTo=(opts,...args)=>oldFly({...opts,duration:0},...args);}
if(map)map.once('load',()=>{sourceFuel=null;refresh();});refresh();
window.FUELWATCH_UPGRADE={switchSection,cache,sourceData};
})();
window.addEventListener('load',()=>{if(map)map.resize();});
if(map)map.once('load',()=>{map.resize();requestAnimationFrame(()=>map.resize());});
// Show applicability at a glance, before opening details.
document.querySelectorAll('.utility-card').forEach((card,i)=>{const category=window.FUELWATCH_UTILITIES.categories[i];const note=document.createElement('p');note.textContent={water:'Average basic charge · bill additions excluded',electricity:'Residential reference · shop tariff unverified',lpg:'Household cylinder survey · archived period'}[category.id];card.querySelector('button').before(note);});
