import {createRequire} from 'node:module';import{mkdir,writeFile,appendFile}from'node:fs/promises';
const root='D:/blender/FuelWatch';await mkdir(root+'/docs/qa-temp',{recursive:true});process.env.TEMP=root+'/docs/qa-temp';process.env.TMP=process.env.TEMP;
const require=createRequire('C:/Users/73405/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json');
const {chromium}=require('playwright');const ctx=await chromium.launchPersistentContext(root+'/docs/qa-profile',{headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',viewport:{width:1440,height:1050},acceptDownloads:false,downloadsPath:root+'/docs/downloads',args:['--disable-crash-reporter','--disable-breakpad','--enable-webgl','--ignore-gpu-blocklist']});
const page=ctx.pages()[0]||await ctx.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{await page.goto('file:///D:/blender/FuelWatch/index.html');await page.waitForFunction(()=>typeof ready!=='undefined'&&ready,{timeout:60000});await page.waitForFunction(()=>map.queryRenderedFeatures({layers:['clusters','points']}).length>0,{timeout:60000});await page.waitForTimeout(1500);
const initial=await page.evaluate(()=>({stations:stations.length,features:map.getSource('stations')._data.features.length,priced:features().features.filter(f=>f.properties.price>=0).length,canvas:!!map.getCanvas(),loaded:map.isStyleLoaded(),rendered:map.queryRenderedFeatures({layers:['clusters','points']}).length}));if(initial.features!==10842)throw Error('all map features not loaded');console.log('BROWSER initial '+JSON.stringify(initial));
await page.screenshot({path:root+'/docs/home-verified.png',fullPage:true});await page.getByRole('button',{name:'Clear',exact:true}).click();await page.waitForFunction(()=>map.getSource('stations')._data.features.length===0);await page.getByRole('button',{name:'Select all',exact:true}).click();await page.waitForFunction(()=>map.getSource('stations')._data.features.length===10842);
await page.getByRole('button',{name:'Premium 95',exact:true}).click();const wrong=await page.evaluate(()=>features().features.filter(f=>f.properties.price>=0&&f.properties.brand!=='Shell').length);if(wrong)throw Error('cross-brand price leakage');await page.getByRole('button',{name:'Diesel 柴油',exact:true}).click();await page.getByRole('button',{name:'Metro Manila prices',exact:true}).click();await page.waitForTimeout(3000);
const target=await page.evaluate(()=>{const s=stations.find(s=>getPrice(s)&&s.brand==='PTT');if(!s)throw Error('No PTT matched station');map.jumpTo({center:[s.lon,s.lat],zoom:14});return s;});await page.waitForTimeout(2000);const pixel=await page.evaluate(s=>map.project([s.lon,s.lat]),target);const box=await page.locator('#map').boundingBox();await page.mouse.click(box.x+pixel.x,box.y+pixel.y);await page.waitForSelector('.maplibregl-popup');await page.screenshot({path:root+'/docs/map-verified.png',fullPage:true});
console.log('BROWSER filters=pass; ron95_no_cross_brand=pass; map_point_popup=pass');
await ctx.grantPermissions(['geolocation']);await ctx.setGeolocation({latitude:target.lat,longitude:target.lon});await page.getByRole('button',{name:'Find cheapest near me'}).click();await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('Lowest available reference'),{timeout:18000});console.log('BROWSER nearby=pass');await page.setViewportSize({width:390,height:844});await page.screenshot({path:root+'/docs/mobile-verified.png',fullPage:true});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(overflow)throw Error('Mobile horizontal overflow');if(errors.length)throw Error(errors.join('\n'));console.log('BROWSER mobile_overflow=0; page_errors=0');await writeFile(root+'/docs/browser-results-verified.json',JSON.stringify({initial,filters:true,ron95NoCrossBrand:true,popup:true,nearby:true,mobileOverflow:false,errors},null,2),{flag:'wx'});await appendFile(root+'/PROGRESS.md','\n轮次 5 浏览器结果：本地 file:// 模式地图实际加载 10842 features；品牌清空/全选、95 不跨品牌、点位弹窗、附近定位比较通过；手机无横向溢出；截图 docs/home.png, map.png, mobile.png。\n');}finally{await ctx.close();}
