import{createRequire}from'node:module';import{mkdir,writeFile}from'node:fs/promises';
const root='D:/blender/FuelWatch';await mkdir(root+'/work/upgrade-oct05/browser',{recursive:true});process.env.TEMP=root+'/work/upgrade-oct05/browser';process.env.TMP=process.env.TEMP;
const require=createRequire('C:/Users/73405/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json');const{chromium}=require('playwright');
const ctx=await chromium.launchPersistentContext(root+'/docs/qa-profile',{headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',viewport:{width:1440,height:1050},args:['--disable-crash-reporter','--disable-breakpad','--enable-webgl','--ignore-gpu-blocklist']});const page=ctx.pages()[0]||await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
try{await page.goto('file:///D:/blender/FuelWatch/index.html');await page.waitForFunction(()=>typeof ready!=='undefined'&&ready&&map.queryRenderedFeatures({layers:['points']}).length>=10500,null,{timeout:60000});await page.waitForTimeout(1000);await page.screenshot({path:root+'/docs/upgrade-fuel.png',fullPage:true});
const initial=await page.evaluate(()=>({rendered:map.queryRenderedFeatures({layers:['points']}).length,source:map.getSource('stations')._data.features.length}));
await page.getByRole('button',{name:'Clear',exact:true}).click();await page.waitForFunction(()=>map.queryRenderedFeatures({layers:['points']}).length===0);const after=await page.evaluate(()=>map.getSource('stations')._data.features.length);if(after!==10842)throw Error('Filter should retain all cached source features');await page.getByRole('button',{name:'Select all',exact:true}).click();await page.getByRole('searchbox',{name:'Search brands'}).fill('PTT');const visible=await page.locator('.brand:visible').count();if(visible!==1)throw Error('Brand search failed');await page.getByRole('searchbox',{name:'Search brands'}).fill('');
await page.getByRole('button',{name:'Utilities overview',exact:true}).click();if(await page.locator('.utility-card').count()!==4)throw Error('Four utility categories required');await page.screenshot({path:root+'/docs/upgrade-utilities.png',fullPage:true});await page.getByRole('button',{name:'Natural gas 天然气',exact:true}).click();if(!(await page.locator('.utility-detail').innerText()).includes('No verified price'))throw Error('Natural gas must not invent price');await page.getByRole('button',{name:'Water 水价',exact:true}).click();if(!await page.locator('.utility-detail a').getAttribute('href'))throw Error('Source link required');
await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Utilities overview',exact:true}).click();await page.screenshot({path:root+'/docs/upgrade-mobile.png',fullPage:true});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');if(errors.length)throw Error(errors.join('\n'));
const result={initial,brandFilterRetainsCachedSource:after,brandSearchVisible:visible,utilityCards:4,naturalGasHonest:true,mobileOverflow:false,errors};console.log('PASS upgrade browser '+JSON.stringify(result));await writeFile(root+'/docs/upgrade-browser-results.json',JSON.stringify(result,null,2),{flag:'wx'});}finally{await ctx.close();}
